import { motion } from 'framer-motion';
import { Sparkles, TrendingUp, AlertTriangle, Users, Package, DollarSign } from 'lucide-react';

const detailedInsights = [
  {
    id: 1,
    category: "Revenue",
    icon: DollarSign,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10",
    title: "Weekend Sales Spike Discovered",
    description: "Our ML models detected a consistent 35% revenue increase during weekends compared to weekdays over the last quarter. This pattern holds true across 80% of categories.",
    impact: "High",
    confidence: 96,
    action: "Focus marketing spend to start Thursday evenings."
  },
  {
    id: 2,
    category: "Product Performance",
    icon: Package,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    title: "Rising Star: Wireless Earbuds",
    description: "Product 'Wireless Earbuds' shows an abnormal 42% week-over-week growth. Sentiment analysis on recent purchases indicates high satisfaction with battery life.",
    impact: "Medium",
    confidence: 89,
    action: "Increase inventory cover from 2 to 6 weeks."
  },
  {
    id: 3,
    category: "Customer Behavior",
    icon: Users,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    title: "Churn Risk in Segment C",
    description: "Active customers in the 'Budget Shopper' segment have reduced their visit frequency from 2.4 to 1.1 times per month. Price elasticity analysis suggests sensitivity to recent shipping fee changes.",
    impact: "High",
    confidence: 92,
    action: "Create targeted free-shipping promotion for Segment C."
  },
  {
    id: 4,
    category: "Inventory Warning",
    icon: AlertTriangle,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
    title: "Potential Stockout: Winter Gear",
    description: "Based on weather forecasts and historical purchasing rates, 4 SKU variants in 'Winter Apparel' will stock out in 14 days, before the next scheduled restock.",
    impact: "Critical",
    confidence: 98,
    action: "Expedite supplier order #8492."
  },
  {
    id: 5,
    category: "Sales Trend",
    icon: TrendingUp,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
    title: "Cross-Selling Opportunity Found",
    description: "Association rule mining revealed that 68% of customers buying 'Yoga Mats' also purchase 'Water Bottles' within 7 days. These items are currently displayed in different categories.",
    impact: "Medium",
    confidence: 85,
    action: "Bundle items or place them adjacent in UI."
  }
];

export default function AIInsights() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Insights Feed</h1>
          <p className="text-muted-foreground mt-1">Automated findings generated by DecisionGPT from your dataset.</p>
        </div>
        <button className="flex items-center gap-2 bg-secondary hover:bg-secondary/80 text-foreground px-4 py-2 rounded-lg font-medium transition-all border border-border">
          <Sparkles size={18} className="text-primary" />
          Re-run Analysis
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 mb-8">
        {[
          { label: "Insights Generated", value: "24", sub: "Last 7 days" },
          { label: "Data Points Analyzed", value: "1.2M", sub: "Across 4 datasets" },
          { label: "Average Confidence", value: "91%", sub: "High reliability" },
          { label: "Actions Taken", value: "12", sub: "From recommendations" }
        ].map((stat, i) => (
          <div key={i} className="bg-card border border-border rounded-xl p-4 flex flex-col">
            <span className="text-sm font-medium text-muted-foreground">{stat.label}</span>
            <div className="flex items-end gap-2 mt-1">
              <span className="text-2xl font-bold">{stat.value}</span>
              <span className="text-xs text-muted-foreground mb-1">{stat.sub}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {detailedInsights.map((insight, i) => (
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            key={insight.id}
            className="glass rounded-xl p-6 shadow-sm border border-border/50 hover:border-primary/50 transition-all group flex flex-col relative overflow-hidden"
          >
            {/* Background Glow */}
            <div className={`absolute -right-20 -top-20 w-40 h-40 rounded-full blur-3xl opacity-20 group-hover:opacity-40 transition-opacity ${insight.bgColor.replace('/10', '')}`} />
            
            <div className="flex justify-between items-start mb-4 relative z-10">
              <div className={`p-3 rounded-xl ${insight.bgColor} ${insight.color}`}>
                <insight.icon size={24} />
              </div>
              <div className="flex flex-col items-end">
                <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1">
                  {insight.category}
                </span>
                <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-green-500/10 text-green-600 dark:text-green-400 border border-green-500/20">
                  {insight.confidence}% Match
                </span>
              </div>
            </div>

            <h3 className="text-xl font-bold mb-3 relative z-10">{insight.title}</h3>
            <p className="text-muted-foreground text-sm leading-relaxed flex-1 relative z-10">
              {insight.description}
            </p>

            <div className="mt-6 pt-5 border-t border-border relative z-10">
              <div className="flex flex-col gap-2">
                <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Suggested Action</span>
                <p className="text-sm font-medium text-foreground">{insight.action}</p>
              </div>
              
              <div className="mt-5 flex gap-3">
                <button className="flex-1 bg-primary text-primary-foreground py-2 rounded-lg text-sm font-semibold hover:bg-primary-hover transition-colors shadow-sm shadow-primary/20">
                  Apply Action
                </button>
                <button className="px-4 py-2 border border-border rounded-lg text-sm font-medium hover:bg-secondary transition-colors text-muted-foreground">
                  Dismiss
                </button>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
