import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { 
  ShieldAlert, 
  PackageX, 
  ArrowRight,
  CheckCircle2,
  Clock,
  TrendingDown,
  BellRing
} from 'lucide-react';

export default function Alerts() {
  const navigate = useNavigate();
  const [acknowledged, setAcknowledged] = useState(false);

  const container = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };

  const item = {
    hidden: { y: 20, opacity: 0, scale: 0.98 },
    show: { y: 0, opacity: 1, scale: 1, transition: { type: "spring" as const, stiffness: 300, damping: 24 } }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto pt-4 pb-12">
      {/* Header */}
      <div className="flex justify-between items-end mb-8">
        <div>
          <div className="flex items-center gap-3 mb-2">
             <div className="p-2 bg-red-100 dark:bg-red-500/20 text-red-600 dark:text-red-500 rounded-xl">
               <BellRing size={24} />
             </div>
             <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
               Action Center
             </h1>
          </div>
          <p className="text-gray-500 dark:text-gray-400 mt-1 pl-12 text-sm">
            Critical business alerts generated by predictive AI models.
          </p>
        </div>
      </div>

      <motion.div variants={container} initial="hidden" animate="show" className="space-y-6">
        
        {/* Core Requested Alert Structure */}
        <AnimatePresence>
          {!acknowledged && (
            <motion.div 
              variants={item}
              exit={{ opacity: 0, x: -100, scale: 0.95 }}
              className="relative overflow-hidden rounded-[2rem] border border-red-200 dark:border-red-900/50 bg-gradient-to-br from-red-50 to-white dark:from-red-950/20 dark:to-zinc-900 shadow-lg shadow-red-500/5"
            >
              {/* Top Warning Ribbon */}
              <div className="w-full bg-red-500 text-white py-1.5 px-6 font-bold text-xs uppercase tracking-widest flex items-center gap-2 shadow-sm relative z-10">
                <ShieldAlert size={14} /> Action Required
              </div>

              <div className="p-8 flex flex-col md:flex-row gap-8 relative z-10">
                
                {/* Large Icon Context */}
                <div className="hidden md:flex flex-shrink-0 items-center justify-center w-24 h-24 bg-red-100 dark:bg-red-900/30 rounded-full border-4 border-white dark:border-zinc-800 shadow-inner">
                  <PackageX size={40} className="text-red-500" />
                </div>

                {/* Main Content */}
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-xs font-bold text-red-600 dark:text-red-400 uppercase tracking-widest bg-red-100 dark:bg-red-900/40 px-2.5 py-0.5 rounded-full">
                      Inventory Alert
                    </span>
                    <span className="text-xs font-medium text-gray-400 flex items-center gap-1">
                      <Clock size={12}/> Just now
                    </span>
                  </div>
                  
                  <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-3 tracking-tight">
                    Forecasted demand exceeds current safety stock indices for top products.
                  </h2>
                  
                  <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-6 font-medium">
                    The AI prediction engine indicates an upcoming surge in sales volume for your primary products over the next 14 days. Current on-hand inventory limits predict a 100% stockout risk unless immediate action is taken.
                  </p>

                  <div className="flex flex-col sm:flex-row gap-3">
                    <button onClick={() => navigate('/data')} className="flex items-center justify-center gap-2 px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-xl shadow-md transition-all active:scale-95">
                      Review Stock Ordering <ArrowRight size={18} />
                    </button>
                    <button 
                      onClick={() => setAcknowledged(true)}
                      className="px-6 py-3 bg-white dark:bg-zinc-800 hover:bg-gray-50 dark:hover:bg-zinc-700 text-gray-700 dark:text-gray-200 border border-gray-200 dark:border-gray-700 font-semibold rounded-xl transition-all"
                    >
                      Acknowledge
                    </button>
                  </div>
                </div>
              </div>

              {/* Decorative Background Icon */}
              <div className="absolute -right-10 -bottom-16 text-red-500/5 dark:text-red-500/10 pointer-events-none">
                <PackageX size={300} />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Example Minor Alert */}
        <motion.div 
          variants={item}
          className="relative overflow-hidden rounded-3xl border border-amber-200 dark:border-amber-900/30 bg-gradient-to-br from-amber-50/50 to-white dark:from-amber-900/10 dark:to-zinc-900/50 p-6 flex flex-col sm:flex-row gap-5 items-start sm:items-center"
        >
           <div className="p-3 bg-amber-100 dark:bg-amber-500/20 text-amber-600 dark:text-amber-500 rounded-xl shrink-0">
             <TrendingDown size={24} />
           </div>
           <div className="flex-1">
              <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100 mb-1">Conversion Drop Detected</h3>
              <p className="text-gray-600 dark:text-gray-400 text-sm">A 4% drop in average transactional revenue was detected over the last weekend.</p>
           </div>
           <button onClick={() => navigate('/analytics')} className="px-4 py-2 bg-white dark:bg-zinc-800 text-amber-700 dark:text-amber-400 font-semibold rounded-lg text-sm border border-amber-200 dark:border-amber-900/50 shadow-sm hover:shadow transition-shadow">
             Investigate
           </button>
        </motion.div>

        {acknowledged && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
            className="p-12 text-center flex flex-col items-center justify-center text-gray-400 border-2 border-dashed border-gray-200 dark:border-gray-800 rounded-3xl bg-gray-50/50 dark:bg-zinc-900/30"
          >
             <CheckCircle2 size={48} className="text-emerald-500 mb-4 opacity-80" />
             <h3 className="text-xl font-bold text-gray-700 dark:text-gray-200 mb-2">All Caught Up</h3>
             <p className="max-w-sm">There are no more critical alerts requiring your immediate attention.</p>
          </motion.div>
        )}

      </motion.div>
    </div>
  );
}
